import { useState } from "react";
import { Link } from "react-router-dom";
import { Mail, ArrowLeft, CheckCircle, KeyRound } from "lucide-react";
import { forgotPassword } from "../../services/authService";

function ForgetPassword() {
  const [email,setEmail]=useState(""); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const handleSubmit=async(e)=>{e.preventDefault();setError("");if(!email.trim())return setError("Please enter your email address.");try{setLoading(true);await forgotPassword(email.trim());setSubmitted(true);}catch(err){setError(err.message||"Unable to process the request.");}finally{setLoading(false);}};
  return <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4 py-10"><div className="w-full max-w-md"><div className="bg-white rounded-2xl border shadow-sm p-8">{!submitted?<><div className="w-14 h-14 mx-auto bg-blue-100 text-blue-600 rounded-2xl flex items-center justify-center"><KeyRound size={28}/></div><div className="text-center mt-5"><h1 className="text-2xl font-bold">Forgot Password?</h1><p className="text-gray-500 mt-2 text-sm">Enter your email address and we'll process your reset request.</p></div>{error&&<div className="mt-5 bg-red-50 border border-red-200 text-red-600 rounded-xl p-3 text-sm">{error}</div>}<form onSubmit={handleSubmit} className="mt-6 space-y-5"><div><label className="block text-sm font-medium text-gray-700 mb-2">Email Address</label><div className="relative"><Mail size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input type="email" value={email} onChange={e=>{setEmail(e.target.value);setError("")}} placeholder="Enter your email" className="w-full pl-10 pr-4 py-3 border rounded-xl outline-none focus:ring-2 focus:ring-blue-500" required/></div></div><button disabled={loading} className="w-full bg-blue-600 disabled:bg-blue-400 text-white py-3 rounded-xl font-semibold">{loading?"Sending...":"Reset Password"}</button></form><Link to="/login" className="mt-6 inline-flex items-center justify-center gap-2 w-full text-sm text-gray-600"><ArrowLeft size={16}/>Back to Login</Link></>:<><div className="w-14 h-14 mx-auto bg-green-100 text-green-600 rounded-2xl flex items-center justify-center"><CheckCircle size={28}/></div><div className="text-center mt-5"><h1 className="text-2xl font-bold">Request Received</h1><p className="text-gray-500 mt-3 text-sm">Your password reset request was found in the server database and has been received.</p></div><Link to="/login" className="mt-7 w-full inline-flex items-center justify-center gap-2 bg-blue-600 text-white py-3 rounded-xl font-semibold"><ArrowLeft size={17}/>Back to Login</Link></>}</div></div></div>;
}
export default ForgetPassword;
