import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Package, ShoppingCart, Users, Banknote, Plus, ArrowRight, Clock, CheckCircle, Truck, XCircle, CalendarDays } from "lucide-react";
import { getProducts } from "../../services/productService";
import { getAdminUsers } from "../../services/userService";
import { getAllOrders } from "../../services/orderService";

const money = (value) => `Rs. ${Number(value || 0).toLocaleString("en-PK")}`;
const statusOf = (order) => String(order?.status || "Pending").toLowerCase();
function Dashboard() {
  const [products,setProducts]=useState([]),[users,setUsers]=useState([]),[orders,setOrders]=useState([]),[dateRange,setDateRange]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=async()=>{try{setLoading(true);setError("");const [p,u,o]=await Promise.all([getProducts(),getAdminUsers(),getAllOrders()]);setProducts(p);setUsers(u);setOrders(o);}catch(e){setError(e.message||"Failed to load dashboard");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const filteredOrders=useMemo(()=>{if(dateRange==="all")return orders;const cutoff=Date.now()-Number(dateRange)*86400000;return orders.filter(o=>new Date(o.createdAt||0).getTime()>=cutoff);},[orders,dateRange]);
  const activeOrders=filteredOrders.filter(o=>statusOf(o)!=="delivered");
  const counts={processing:filteredOrders.filter(o=>statusOf(o)==="processing"||statusOf(o)==="pending").length,shipped:filteredOrders.filter(o=>statusOf(o)==="shipped").length,delivered:filteredOrders.filter(o=>statusOf(o)==="delivered").length,cancelled:filteredOrders.filter(o=>statusOf(o)==="cancelled").length};
  const values={processing:filteredOrders.filter(o=>["processing","pending"].includes(statusOf(o))).reduce((s,o)=>s+Number(o.total||0),0),shipped:filteredOrders.filter(o=>statusOf(o)==="shipped").reduce((s,o)=>s+Number(o.total||0),0),delivered:filteredOrders.filter(o=>statusOf(o)==="delivered").reduce((s,o)=>s+Number(o.total||0),0),cancelled:filteredOrders.filter(o=>statusOf(o)==="cancelled").reduce((s,o)=>s+Number(o.total||0),0)};
  const recent=[...filteredOrders].sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0)).slice(0,5);
  if(loading)return <div className="min-h-[60vh] flex items-center justify-center text-gray-500">Loading dashboard...</div>;
  return <div className="min-h-screen bg-gray-50 p-6 md:p-8"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5 mb-8"><div><h1 className="text-3xl font-bold">Admin Dashboard</h1><p className="text-gray-500 mt-1">Live data from MongoDB.</p></div><div className="flex gap-3"><label className="inline-flex items-center gap-2 bg-white border rounded-xl px-4 py-3"><CalendarDays size={17}/><select value={dateRange} onChange={e=>setDateRange(e.target.value)} className="bg-transparent outline-none"><option value="all">All time</option><option value="28">Last 28 days</option><option value="90">Last 3 months</option><option value="365">Last year</option></select></label><Link to="/admin/products/add" className="inline-flex items-center gap-2 bg-blue-600 text-white px-5 py-3 rounded-xl font-semibold"><Plus size={18}/>Add Product</Link></div></div>
    {error&&<div className="mb-6 bg-red-50 border border-red-200 text-red-600 rounded-xl p-4">{error}</div>}
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5 mb-8"><StatCard title="Total Products" value={products.length} icon={Package} link="/admin/products"/><StatCard title="Active Orders" value={activeOrders.length} icon={ShoppingCart} link="/admin/orders"/><StatCard title="Total Users" value={users.length} icon={Users} link="/admin/users"/><div className="bg-white rounded-2xl border shadow-sm p-6"><p className="text-sm text-gray-500">Active Order Value</p><h2 className="text-2xl font-bold mt-2">{money(values.processing+values.shipped)}</h2><div className="mt-5"><Banknote className="text-green-600"/></div></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5 mb-8">{[["Processing",values.processing,counts.processing,Clock,"yellow"],["Shipped",values.shipped,counts.shipped,Truck,"blue"],["Delivered",values.delivered,counts.delivered,CheckCircle,"green"],["Cancelled",values.cancelled,counts.cancelled,XCircle,"red"]].map(([label,value,count,Icon])=><div key={label} className="bg-white rounded-2xl border shadow-sm p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-gray-500">{label}</p><p className="text-2xl font-bold mt-2">{money(value)}</p></div><Icon size={24}/></div><p className="text-xs text-gray-500 mt-4">{count} orders</p></div>)}</div>
    <div className="bg-white rounded-2xl border shadow-sm overflow-hidden"><div className="flex items-center justify-between p-6 border-b"><div><h2 className="text-xl font-bold">Recent Orders</h2><p className="text-sm text-gray-500">Live order records.</p></div><Link to="/admin/orders" className="text-blue-600 font-semibold">View All <ArrowRight size={16} className="inline"/></Link></div>{recent.length===0?<div className="p-12 text-center text-gray-500">No orders yet.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[750px]"><thead className="bg-gray-50"><tr><th className="text-left px-6 py-4">Order</th><th className="text-left px-6 py-4">Customer</th><th className="text-left px-6 py-4">Date</th><th className="text-left px-6 py-4">Total</th><th className="text-left px-6 py-4">Status</th></tr></thead><tbody className="divide-y">{recent.map(o=><tr key={o._id}><td className="px-6 py-4 font-bold">#{o.orderNumber||o._id}</td><td className="px-6 py-4">{o.customer?.fullName}<div className="text-sm text-gray-500">{o.customer?.email}</div></td><td className="px-6 py-4">{o.createdAt?new Date(o.createdAt).toLocaleDateString("en-PK"):"-"}</td><td className="px-6 py-4 font-bold">{money(o.total)}</td><td className="px-6 py-4">{o.status}</td></tr>)}</tbody></table></div>}</div>
  </div>;
}
function StatCard({title,value,icon:Icon,link}){return <div className="bg-white rounded-2xl border shadow-sm p-6"><div className="flex justify-between"><div><p className="text-sm text-gray-500">{title}</p><h2 className="text-3xl font-bold mt-2">{value}</h2></div><Icon className="text-blue-600"/></div><Link to={link} className="inline-block mt-5 text-sm text-blue-600 font-semibold">Manage <ArrowRight size={15} className="inline"/></Link></div>}
export default Dashboard;
